# Generated by Django 3.2 on 2021-06-12 21:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import user.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('is_doctor', models.SmallIntegerField()),
                ('last_login', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_joined', models.DateField(default=user.models.get_now_date)),
                ('freeze', models.BooleanField(default=False)),
            ],
            managers=[
                ('objects', user.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('phone', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='UserCods',
            fields=[
                ('phone', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('code', models.IntegerField(null=True)),
                ('code_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='user.user')),
                ('birth_day', models.DateField()),
                ('polis', models.CharField(max_length=16, null=True)),
            ],
        ),
    ]
