# Generated by Django 3.2 on 2021-06-09 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='user.user')),
                ('cost', models.IntegerField(null=True)),
                ('experience', models.TextField(null=True)),
                ('service_types', models.TextField(null=True)),
                ('work_time', models.TextField(null=True)),
                ('educations', models.TextField(null=True)),
                ('extra_field', models.TextField(null=True)),
                ('specifications', models.ManyToManyField(to='doctor.Specialization')),
            ],
        ),
    ]
